ECHO:
START 
adb shell pm uninstall -k --user 0 com.sec.android.app.shealth
adb shell pm uninstall -k --user 0 com.samsung.android.calendar
adb shell pm uninstall -k --user 0 com.samsung.android.samsungpass
adb shell pm uninstall -k --user 0 com.samsung.android.spayfw
adb shell pm uninstall -k --user 0 com.samsung.android.spay
adb shell pm uninstall -k --user 0 com.samsung.android.scloud
adb shell pm uninstall -k --user 0 com.samsung.android.app.galaxyfinder
adb shell pm uninstall -k --user 0 com.sec.android.app.sbrowser
adb shell pm uninstall -k --user 0 com.samsung.android.email.provider
adb shell pm uninstall -k --user 0 com.android.providers.userdictionary
adb shell pm uninstall -k --user 0 com.sec.android.app.dictionary
adb shell pm uninstall -k --user 0 com.samsung.voiceserviceplatform
adb shell pm uninstall -k --user 0 com.samsung.svoice.sync
adb shell pm uninstall -k --user 0 com.samsung.android.voicewakeup
adb shell pm uninstall -k --user 0 com.sec.svoice.lang.de_DE
adb shell pm uninstall -k --user 0 com.sec.svoice.lang.es_ES
adb shell pm uninstall -k --user 0 com.sec.svoice.lang.fr_FR
adb shell pm uninstall -k --user 0 com.sec.svoice.lang.it_IT
adb shell pm uninstall -k --user 0 com.sec.svoice.lang.ru_RU
adb shell pm uninstall -k --user 0 com.samsung.android.themestore
adb shell pm uninstall -k --user 0 com.samsung.android.themecenter
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.samsungapps
adb shell pm uninstall -k --user 0 com.samsung.android.weather
adb shell pm uninstall -k --user 0 com.samsung.android.app.memo
adb shell pm uninstall -k --user 0 com.sec.android.app.music
adb shell pm uninstall -k --user 0 com.samsung.android.fmm
adb shell pm uninstall -k --user 0 com.sec.android.app.fm
adb shell pm uninstall -k --user 0 com.sec.android.widgetapp.webmanual
adb shell pm uninstall -k --user 0 com.sec.android.app.samsungapps
adb shell pm uninstall -k --user 0 com.sec.android.gallery3d
adb shell pm uninstall -k --user 0 com.samsung.android.videolist
adb shell pm uninstall -k --user 0 com.samsung.android.video
adb shell pm uninstall -k --user 0 com.sec.android.app.voicenote
adb shell pm uninstall -k --user 0 com.sec.android.daemonapp 
adb shell pm uninstall -k --user 0 de.axelspringer.yana.zeropage
adb shell pm uninstall -k --user 0 com.osp.app.signin
adb shell pm uninstall -k --user 0 com.sec.android.app.billing
adb shell pm uninstall -k --user 0 com.samsung.storyservice
adb shell pm uninstall -k --user 0 com.sec.factory.camera
adb shell pm uninstall -k --user 0 com.sec.android.app.camera
adb shell pm uninstall -k --user 0 com.samsung.android.game.gamehome
adb shell pm uninstall -k --user 0 com.samsung.android.game.gametools
adb shell pm uninstall -k --user 0 com.samsung.faceservice
adb shell pm uninstall -k --user 0 com.skype.raider
adb shell pm uninstall -k --user 0 com.microsoft.office.word
adb shell pm uninstall -k --user 0 com.microsoft.office.excel
adb shell pm uninstall -k --user 0 com.microsoft.office.powerpoint
adb shell pm uninstall -k --user 0 com.microsoft.office.onenote
adb shell pm uninstall -k --user 0 com.microsoft.skydrive
adb shell pm uninstall -k --user 0 com.google.android.gm
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.android.talk
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 flipboard.boxer.app
adb shell pm uninstall -k --user 0 com.samsung.android.easysetup
adb shell pm uninstall -k --user 0 com.enhance.gameservice
adb shell pm uninstall -k --user 0 com.samsung.android.authfw
adb shell pm uninstall -k --user 0 com.samsung.android.beaconmanager
adb shell pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
adb shell pm uninstall -k --user 0 com.samsung.app.newtrim
adb shell pm uninstall -k --user 0 com.samsung.android.lool
adb shell pm uninstall -k --user 0 com.samsung.android.provider.filterprovider
adb shell pm uninstall -k --user 0 com.samsung.android.provider.shootingmodeprovider
adb shell pm uninstall -k --user 0 com.samsung.android.drivelink.stub
adb shell pm uninstall -k --user 0 com.samsung.android.smartface
adb shell pm uninstall -k --user 0 com.samsung.android.providers.context
adb shell pm uninstall -k --user 0 com.samsung.android.app.colorblind
adb shell pm uninstall -k --user 0 com.sec.app.samsungprintservice
adb shell pm uninstall -k --user 0 com.samsung.android.app.talkback
adb shell pm uninstall -k --user 0 com.samsung.android.app.simplesharing
adb shell pm uninstall -k --user 0 com.samsung.android.location
adb shell pm uninstall -k --user 0 com.samsung.android.app.mirrorlink
adb shell pm uninstall -k --user 0 com.samsung.android.sm
adb shell pm uninstall -k --user 0 com.samsung.android.allshare.service.fileshare
adb shell pm uninstall -k --user 0 com.samsung.android.app.filterinstaller
adb shell pm uninstall -k --user 0 com.samsung.safetyinformation
adb shell pm uninstall -k --user 0 com.samsung.android.oneconnect
adb shell pm uninstall -k --user 0 com.samsung.android.svcagent
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.handwriting